config/routes.rb
ProtoDough::Application.routes.draw do
	resources :posts
	get "my_posts" => "posts#my_posts", as: "my_posts"

	root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
  
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    
  end

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :originality, :impact, :measurability, :practicality, :applicability, presence: true,
		numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }  
	validates :comment, presence: true, length: { in: 3..140 }

end

app/models/post.rb
class Post < ActiveRecord::Base
	#establishing relationship to users
	belongs_to :user
	# each post can have many evaluations
	has_many :evaluations
	validates_associated :evaluations

	validates :title, presence: true, uniqueness: true, length: { in: 5..60 }
	validates :tagline, :product_type, :customer, :task, :removing, :enabling, :category, presence: true 

	scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :evaluations

	# Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged

  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Pagination
  paginates_per 100

  # Validations
  # :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  validates :username, length: { in: 4..15 }
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def self.paged(page_number)
    order(admin: :desc, username: :asc).page page_number
  end

  def self.search_and_order(search, page_number)
    if search
      where("username LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, username: :asc
      ).page page_number
    else
      order(admin: :desc, username: :asc).page page_number
    end
  end

  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","username","slug","created_at")
  end

  def self.last_signins(count)
    order(last_sign_in_at:
    :desc).limit(count).select("id","username","slug","last_sign_in_at")
  end

  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!

  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @count = User.users_count
    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]


  def index
    @users = User.search_and_order(params[:search], params[:page])
  end

  def show
    redirect_to edit_admin_user_path(params[:id])
  end

  def edit
  end

  def update
    old_username = @user.username
    new_params = user_params.dup
    new_params[:username] = new_params[:username].strip
    new_params[:email] = new_params[:email].strip

    @user.username = new_params[:username]
    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0

    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end

    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.username} updated."
    else
      flash[:alert] = "#{old_username} couldn't be updated."
      render :edit
    end
  end


  private

  def set_user
    @user = User.friendly.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(
    :username,
    :email,
    :password,
    :password_confirmation,
    :admin,
    :locked
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :reject_locked!, if: :devise_controller?


  # Devise permitted params
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
      :username,
      :email,
      :password,
      :password_confirmation)
    }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(
      :username,
      :email,
      :password,
      :password_confirmation,
      :current_password
      )
    }
  end

  # Redirects on successful sign in
  def after_sign_in_path_for(resource)
    inside_path
  end

  # Auto-sign out locked users
  def reject_locked!
    if current_user && current_user.locked?
      sign_out current_user
      user_session = nil
      current_user = nil
      flash[:alert] = "Your account is locked."
      flash[:notice] = nil
      redirect_to root_url
    end
  end
  helper_method :reject_locked!

  # Only permits admin users
  def require_admin!
    authenticate_user!

    if current_user && !current_user.admin?
      redirect_to root_path
    end
  end
  helper_method :require_admin!

end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
	
	def index
		@evals = Evaluation.all
	end

	def my_evals
		@my_evals = Evaluation.where(user: current_user)
	end

	def show
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private

	def eval_params
		params.require(:evaluation).permit(:originality, :impact, :applicability, :measurability, :practicality, :comment)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [
    :inside
  ]

  def home
  end

  def inside
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!


	def index
    @posts = Post.all
  end

	def my_posts
		@my_posts = Post.where(user: current_user)
	end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

	def edit
		@post = Post.find(params[:id])
	end

  def create
    # Instantiate a new object using for parameters
    @post = Post.new(post_params)
		@post.user = current_user
    # Save the object
    if @post.save
    # If save succeeds, redirect to the index action
      flash[:notice] = "Post created successfully."
      redirect_to(:action => 'index')
    else
    # If save fails, redisplay the form so user cna fix problems
    render('new')
    end
  end

  def update
    # Find an existing object using for parameters
    @post = Post.find(params[:id])
    # Update the object
    if @post.update_attributes(post_params)
    # If update succeeds, redirect to the index action
      flash[:notice] = "Post updated successfully."
      redirect_to(:action => 'show', :id => @post.id)
    else
    # If update fails, redisplay the form so user cna fix problems
    render('edit')
    end
  end

  def destroy
  end

  private

    def post_params
    # same as using "params[:post]", except that it:
    # - raises an error if :post is not present
    # - allows listed attributes to be mass-assigned
      params.require(:post).permit(:category, :title, :tagline, :product_type, :customer, :task, :removing, :enabling, :competitor, :mentorship)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | ProtoDough"
    end
  end
end

app/helpers/email_helper.rb
module EmailHelper
  def line_break(s)
    s.gsub("\n", "<br/>")
  end
end

app/views/admin/base/index.html.erb
<% title("Admin") %>
<h1>Admin <small>Home</small></h1>
<div class="row">
  <div class="col-sm-4">
    <h3>Menu</h3>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= "#{pluralize(@count, 'user')}" %></small></h4>
    
    <hr/>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/admin/users/edit.html.erb
<% title("Edit User Id: #{@user.id}") %>
<div class="row">
  <div class="col-sm-6">
    <h1>
      Edit User <small><%= "#{@user.username.capitalize} - id: #{@user.id}" %></small>
    </h1>
    <p><%= link_to "Back to Users", admin_users_path %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>

    <div class="form-group">
      <%= f.label :username %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :username, :autofocus => true, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>

    <% unless current_user.id == @user.id %>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
        </div>
      </div>
    </div>
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update User", class: "btn btn-danger" %>
      </div>
    </div>

    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<% title("Users Admin") %>
<h1>Users <small>Admin</small></h1>
<p><%= link_to "Back to Admin", admin_root_path %></p>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

<%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
</p>
<% end %>

<table class="table table-striped">
  <tr>
    <th>User ID</th>
    <th>Username</th>
    <th>Admin</th>
    <th>Locked</th>
    <th>Email</th>
    <th>Sign In Count</th>
    <th>Created At</th>
    <th>Last Sign In</th>
    <th>Last Sign In IP</th>
  </tr>

  <% @users.each do |user| %>

  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.username.capitalize, admin_user_path(user) %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.locked? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.email %></td>
    <td><%= user.sign_in_count %></td>
    <td><%= time_ago_in_words(user.created_at) %></td>
    <% unless user.last_sign_in_at.nil? %>
    <td><%= time_ago_in_words(user.last_sign_in_at)%> ago</td>
    <% else %>
    <td>never</td>
    <% end %>
    <td><%= user.last_sign_in_ip %></td>
  </tr>

  <% end %>

</table>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; <%= Time.now.year %> - Yourself!
          <br/>
          Assembled with <%= link_to "RailsBricks", "http://www.railsbricks.net" %>
        </small></p>
      </div>

    </div>

  </div>
</div>
<% if Rails.env == "production" %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-XXXXXX-XX', 'auto');
    ga('send', 'pageview');
  </script>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>
<li><%= link_to "Sign in", new_user_session_path %></li>
<li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
<li><%= link_to "Protected Page", inside_path %></li>
<li><%= link_to "Edit your account", edit_user_registration_path %></li>
<li><%= link_to "My Posts", my_posts_path %></li>
<li><%= link_to "All Posts", posts_path %></li>

<% if current_user.admin? %>
<li><%= link_to "Admin", admin_root_path %></li>
<% end %>

<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "ProtoDough" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<% title("Home Page") %>
<h1><i class="fa fa-home"></i> Home Page <small>views/pages/home.html.erb</small></h1>

app/views/pages/inside.html.erb
<% title("Protected page") %>
<h1>Protected Page</h1>
<p>This page is only visible to signed in users. Edit it at: <em>views/pages/inside.html.erb</em></p>
<p>You can change the page users see after successfully signing in within the method <em>after_sign_in_path_for</em> inside <strong>application_controller.rb</strong></p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<%= form_for(@post) do |f| %>
	<table summary="Update idea form">
	 <tr>
	  <th>Category</th>
	  <td><%= f.text_field :category %></td>
	 </tr>
	 <tr>
	  <th>Name</th>
	  <td><%= f.text_field :title %></td>
	 </tr>
	 <tr>
	  <th>Tagline</th>
	  <td><%= f.text_field :tagline %></td>
	 </tr>
	 <tr>
	  <th>Product type</th>
	  <td><%= f.text_field :product_type %></td>
	 </tr>
	 <tr>
	  <th>helps</th>
	  <td><%= f.text_field :customer %></td>
	 </tr>
	 <tr>
	  <th>by</th>
	  <td><%= f.text_field :task %></td>
	 </tr>
	 <tr>
	  <th>removing</th>
	  <td><%= f.text_field :enabling %></td>
	 </tr>
	 <tr>
	  <th>unlike</th>
	  <td><%= f.text_field :competitor %></td>
	 </tr>
	 <tr>
	  <th>Would you like to request advising?</th>
	  <td><%= f.text_field :mentorship %></td>
	 </tr>
	</table>
	 <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<div class="posts index">
	<h2>Posts</h2>

	<%= link_to("Add New Post", {:action => 'new'}, :class => 'action new') %>
	
		<div class="container">
  			<div class="row">
    			<div class="col-xs-3"></div>
    				<div class="col-xs-9">
    					<div class="row">
						<% @posts.each do |post| %>
							<div class="col-xs-6 col-sm-3">
								<dl>
								  <dt><%= post.title %></dt>
								  <dd><%= post.tagline %></dd>
								  <dd><%= post.category %></dd>
								  <td class="actions">
								  <%= link_to("Show", {:action => 'show', :id => post.id}, :class => 'action show' ) %>
								  <%= link_to("Edit", {:action => 'edit', :id => post.id}, :class => 'action edit' ) %>
								</dl>
							</div>
						<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>

app/views/posts/my_posts.html.erb
<div class="posts index">
	  <h2>My Posts</h2>

		  <%= link_to("Add New Post", {:action => 'new'}, :class => 'action new') %>

			    <div class="container">
			        <div class="row">
			          <div class="col-xs-3"></div>
			            <div class="col-xs-9">
			              <div class="row">
			            <% @my_posts.each do |post| %>
				              <div class="col-xs-6 col-sm-3">
			                <dl>
			                  <dt><%= post.product_name %></dt>
			                  <dd><%= post.tagline %></dd>
			                  <dd><%= post.category %></dd>
			                  <td class="actions">
			                  <%= link_to("Show", {:action => 'show', :id => post.id}, :class => 'action show' ) %>
			                  <%= link_to("Edit", {:action => 'edit', :id => post.id}, :class => 'action edit' ) %>
			                </dl>
			              </div>
			            <% end %>
			            </div>
			          </div>
			        </div>
			      </div>
			    </div>
				</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<%= form_for(:post, :url => {:action => 'create'}) do |f| %>

	<table summary="New idea form">
	 <tr>
	  <th>Category</th>
	  <td><%= f.text_field(:category) %></td>
	 </tr>
	 <tr>
	  <th>Name</th>
	  <td><%= f.text_field(:title) %></td>
	 </tr>
	 <tr>
	  <th>Tagline</th>
	  <td><%= f.text_field(:tagline) %></td>
	 </tr>
	 <tr>
	  <th>Product type</th>
	  <td><%= f.text_field(:product_type) %></td>
	 </tr>
	 <tr>
	  <th>helps</th>
	  <td><%= f.text_field(:customer) %></td>
	 </tr>
	 <tr>
	  <th>by</th>
	  <td><%= f.text_field(:task) %></td>
	 </tr>
	 <tr>
	  <th>removing</th>
	  <td><%= f.text_field(:enabling) %></td>
	 </tr>
	 <tr>
	  <th>unlike</th>
	  <td><%= f.text_field(:competitor) %></td>
	 </tr>
	 <tr>
	  <th>Would you like to request advising?</th>
	  <td><%= f.text_field(:mentorship) %></td>
	 </tr>
	</table>
	 <%= submit_tag("Create Post") %>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>
<table summary="Post detail view">
 <tr>
 	<th>Category</th>
	<td><%= @post.category %></td>
 </tr>
 <tr>
 	<th>Name</th>
	<td><%= @post.title %></td>
 </tr>
 <tr>
 	<th>Tagline</th>
	<td><%= @post.tagline %></td>
 </tr>
 <tr>
 	<th>Type</th>
	<td><%= @post.product_type %></td>
 </tr>
 <tr>
 	<th>helps</th>
	<td><%= @post.customer %></td>
 </tr>
 <tr>
 	<th>by</th>
	<td><%= @post.task %></td>
 </tr>
 <tr>
 	<th>removing</th>
	<td><%= @post.removing %></td>
 </tr>
 <tr>
 	<th>enabling</th>
	<td><%= @post.enabling %></td>
 </tr>
 <tr>
 	<th>unlike</th>
	<td><%= @post.competitor %></td>
 </tr>
 <tr>
 	<th>Request for advising</th>
	<td><%= @post.mentorship ? 'yes' : 'no' %></td>
 </tr>
</table>